### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by devo343** [floriangit/hdd_sound#1]
Would it be possible to make this work with windows? i know this is old but this is the only type of program i can find that does this

**Comment by floriangit** [comment]
This is not going to easily work with Windows. It relies on:
a) libpulseaudio-dev (but this is available in Windows)
b) the inner device driver presentation of hard-disks in Linux

You could go with the header files (these are the WAVE files, but to make it portable I converted them to C code data) and try how playing audio works in Windows programmatically.

**Comment by devo343** [comment]
i acutaly was able to code something similar to this today lol 
https://devodev.itch.io/diskclick

**Comment by floriangit** [comment]
"Sounds" good :-)! I see you have a similar issue as me. The background "white" noise from the recordings is not fully away. My power-supply is so noisy it just adds to those legacy HDD sounds. With fan-less PCs and quiet SSDs these days it would be nice to filter that more out. I have not figured how to do that for my linux version, but I'm not an audio nerd at all. Let me know if you find out!

Thanks!
